name: Project_EXFIL
version: 'v1.14.514'
main: org.nmo.project_exfil.ProjectEXFILPlugin
api-version: '1.21'
authors: [ NJU Minecraft Organization ]
description: Tarkov-like game in Minecraft, a simple paper plugin
website: nmo.net.cn
